/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Revolyssup/kube-client-go/pkg/apis/goglot.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGlotPods implements GlotPodInterface
type FakeGlotPods struct {
	Fake *FakeGoglotV1alpha1
	ns   string
}

var glotpodsResource = schema.GroupVersionResource{Group: "goglot.dev", Version: "v1alpha1", Resource: "glotpods"}

var glotpodsKind = schema.GroupVersionKind{Group: "goglot.dev", Version: "v1alpha1", Kind: "GlotPod"}

// Get takes name of the glotPod, and returns the corresponding glotPod object, and an error if there is any.
func (c *FakeGlotPods) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlotPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(glotpodsResource, c.ns, name), &v1alpha1.GlotPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlotPod), err
}

// List takes label and field selectors, and returns the list of GlotPods that match those selectors.
func (c *FakeGlotPods) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlotPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(glotpodsResource, glotpodsKind, c.ns, opts), &v1alpha1.GlotPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GlotPodList{ListMeta: obj.(*v1alpha1.GlotPodList).ListMeta}
	for _, item := range obj.(*v1alpha1.GlotPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested glotPods.
func (c *FakeGlotPods) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(glotpodsResource, c.ns, opts))

}

// Create takes the representation of a glotPod and creates it.  Returns the server's representation of the glotPod, and an error, if there is any.
func (c *FakeGlotPods) Create(ctx context.Context, glotPod *v1alpha1.GlotPod, opts v1.CreateOptions) (result *v1alpha1.GlotPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(glotpodsResource, c.ns, glotPod), &v1alpha1.GlotPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlotPod), err
}

// Update takes the representation of a glotPod and updates it. Returns the server's representation of the glotPod, and an error, if there is any.
func (c *FakeGlotPods) Update(ctx context.Context, glotPod *v1alpha1.GlotPod, opts v1.UpdateOptions) (result *v1alpha1.GlotPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(glotpodsResource, c.ns, glotPod), &v1alpha1.GlotPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlotPod), err
}

// Delete takes name of the glotPod and deletes it. Returns an error if one occurs.
func (c *FakeGlotPods) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(glotpodsResource, c.ns, name), &v1alpha1.GlotPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGlotPods) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(glotpodsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GlotPodList{})
	return err
}

// Patch applies the patch and returns the patched glotPod.
func (c *FakeGlotPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlotPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(glotpodsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GlotPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlotPod), err
}
